### ISSUE TITLE
IOS导致字体增大，设置font-size无效

### ISSUE THREAD

**Issue by ZTrainWilliams** [ZTrainWilliams/H5_skills#3]
flex布局子项撑满（flex：1或内容撑满）时在IOS中会导致字体增大，设置font-size无效
解决方案：
    text-size-adjust: 检索或设置移动端页面中对象文本的大小调整
``` css
.text{
    text-size-adjust:100%; 
    -ms-text-size-adjust:100%; 
    -moz-text-size-adjust:100%; 
    -webkit-text-size-adjust:100%; 
}
```
