### ISSUE TITLE
ios使用rotateX失效或出现异常

### ISSUE THREAD

**Issue by ZTrainWilliams** [ZTrainWilliams/H5_skills#7]
### ios使用rotateX失效或出现异常
rotateX失效或者是组件调用使用多次的时候，出现某个帧出现异常丢失。
增加上 -webkit- 任然无效，考虑是视角问题。

解决方案：
``` css
/*  父级加上景深属性 */
{
  transform: perspective(1000);
}
```
