### ISSUE TITLE
IOS页面再次滚动进入的时候，页面元素显示缺失，DOM确保已存在

### ISSUE THREAD

**Issue by ZTrainWilliams** [ZTrainWilliams/H5_skills#8]
### 问题表现
元素不再可视区域内，滚动再次进入到该元素位置，元素会出现缺失状况。元素缺失ItemRight > ItemLeft，ItemRight内的元素缺失次数最多。

标签：
``` html
<div class="item">
    <div class="ItemLeft">
    </div>
    <div class="ItemRight">
    </div>
</div>
```
样式：
``` css
.item{
    overflow:hidden;
    display:flex;
}
.ItemLeft{
     display:flex;
}
.ItemRight{
    display:flex;
    overflow-x: scroll;
}
```
### 处理方法：
去除ItemRight的overflow-x: scroll;，元素缺失情况不再出现。
但是overflow-x: scroll;的左右滚动效果保留，则去除item的overflow:hidden；。

### 出现原因（个人理解）
flex+overflow:hidden在ios可能导致：未在可视区域元素渲染的时候，flex导致元素不能完全撑开，而此时父级overflow与子级overflow出现影响而被hidden，所以出现缺失情况。

### 额外阅读
ios下overflow:hidden 无效：  https://www.jianshu.com/p/317e7f87c394
